import { jsPDF } from 'jspdf';
import { Room, Participant, Item, Payment, Currency, CURRENCY_SYMBOLS } from '@/types';
import { getItemTotal, getParticipantTotal, getRoomTotals } from './calculations';

interface PDFGeneratorOptions {
  room: Room;
  participants: Participant[];
  items: Item[];
  payments: Payment[];
  language: 'fr' | 'en';
}

const translations = {
  fr: {
    receipt: 'Reçu',
    date: 'Date',
    participants: 'Participants',
    items: 'Articles',
    subtotal: 'Sous-total',
    tip: 'Pourboire',
    tax: 'Taxes',
    total: 'Total',
    perPerson: 'Par personne',
    paid: 'Payé',
    remaining: 'Restant',
    generatedBy: 'Généré par ReceiptSplit',
  },
  en: {
    receipt: 'Receipt',
    date: 'Date',
    participants: 'Participants',
    items: 'Items',
    subtotal: 'Subtotal',
    tip: 'Tip',
    tax: 'Tax',
    total: 'Total',
    perPerson: 'Per person',
    paid: 'Paid',
    remaining: 'Remaining',
    generatedBy: 'Generated by ReceiptSplit',
  },
};

export function generateReceiptPDF(options: PDFGeneratorOptions): void {
  const { room, participants, items, payments, language } = options;
  const t = translations[language];
  const currency = room.currency as Currency;
  const symbol = CURRENCY_SYMBOLS[currency];

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: [80, 200], // Receipt-style narrow format
  });

  const pageWidth = 80;
  const margin = 5;
  const contentWidth = pageWidth - 2 * margin;

  let y = 10;

  // Helper to format currency
  const formatAmount = (amount: number) => `${symbol}${amount.toFixed(2)}`;

  // Helper to add text
  const addText = (text: string, size: number = 10, align: 'left' | 'center' | 'right' = 'left', bold: boolean = false) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');

    let x = margin;
    if (align === 'center') x = pageWidth / 2;
    if (align === 'right') x = pageWidth - margin;

    doc.text(text, x, y, { align });
  };

  // Helper to add line
  const addLine = () => {
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 3;
  };

  // Header - Logo/Title
  addText('🧾 ReceiptSplit', 14, 'center', true);
  y += 6;
  addText(room.title || t.receipt, 12, 'center', true);
  y += 5;

  // Date
  const date = new Date(room.created_at).toLocaleDateString(language === 'fr' ? 'fr-FR' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  addText(date, 8, 'center');
  y += 6;

  addLine();

  // Participants
  addText(t.participants, 9, 'left', true);
  y += 4;
  participants.forEach(p => {
    addText(`• ${p.name}${p.is_creator ? ' ★' : ''}`, 8);
    y += 3;
  });
  y += 3;

  addLine();

  // Items
  addText(t.items, 9, 'left', true);
  y += 4;

  items.forEach(item => {
    const owner = participants.find(p => p.id === item.created_by_participant_id);
    const itemTotal = getItemTotal(item);

    // Item name and quantity
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const itemName = item.quantity > 1 ? `${item.name} x${item.quantity}` : item.name;
    doc.text(itemName, margin, y);
    doc.text(formatAmount(itemTotal), pageWidth - margin, y, { align: 'right' });
    y += 3;

    // Owner name
    if (owner) {
      doc.setFontSize(6);
      doc.setTextColor(128, 128, 128);
      doc.text(`  → ${owner.name}`, margin, y);
      doc.setTextColor(0, 0, 0);
      y += 3;
    }
  });

  y += 3;
  addLine();

  // Totals
  const roomTotals = getRoomTotals(room, participants, items, payments);

  // Subtotal
  doc.setFontSize(8);
  doc.text(t.subtotal, margin, y);
  doc.text(formatAmount(roomTotals.subtotal), pageWidth - margin, y, { align: 'right' });
  y += 4;

  // Tip
  if (Number(room.tip_percent) > 0) {
    doc.text(`${t.tip} (${room.tip_percent}%)`, margin, y);
    doc.text(formatAmount(roomTotals.tipTotal), pageWidth - margin, y, { align: 'right' });
    y += 4;
  }

  // Tax
  if (Number(room.tax_percent) > 0) {
    doc.text(`${t.tax} (${room.tax_percent}%)`, margin, y);
    doc.text(formatAmount(roomTotals.taxTotal), pageWidth - margin, y, { align: 'right' });
    y += 4;
  }

  addLine();

  // Grand Total
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(t.total, margin, y);
  doc.text(formatAmount(roomTotals.grandTotal), pageWidth - margin, y, { align: 'right' });
  y += 6;

  // Per person breakdown
  if (participants.length > 1) {
    addLine();
    addText(t.perPerson, 9, 'left', true);
    y += 4;

    participants.forEach(p => {
      const pTotal = getParticipantTotal(p.id, items, Number(room.tip_percent), Number(room.tax_percent));
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(p.name, margin, y);
      doc.text(formatAmount(pTotal.total), pageWidth - margin, y, { align: 'right' });
      y += 4;
    });
  }

  // Payment status
  const totalPaid = payments.reduce((sum, p) => sum + Number(p.amount), 0);
  if (totalPaid > 0) {
    y += 2;
    addLine();
    doc.setFontSize(8);
    doc.text(t.paid, margin, y);
    doc.setTextColor(0, 150, 0);
    doc.text(`-${formatAmount(totalPaid)}`, pageWidth - margin, y, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    y += 4;

    const remaining = roomTotals.grandTotal - totalPaid;
    if (remaining > 0) {
      doc.text(t.remaining, margin, y);
      doc.setTextColor(200, 100, 0);
      doc.text(formatAmount(remaining), pageWidth - margin, y, { align: 'right' });
      doc.setTextColor(0, 0, 0);
      y += 4;
    }
  }

  // Footer
  y += 5;
  addLine();
  y += 2;
  doc.setFontSize(6);
  doc.setTextColor(128, 128, 128);
  doc.text(t.generatedBy, pageWidth / 2, y, { align: 'center' });
  y += 3;
  doc.text(new Date().toLocaleString(language === 'fr' ? 'fr-FR' : 'en-US'), pageWidth / 2, y, { align: 'center' });

  // Save
  const filename = `${room.title || 'receipt'}-${room.id}.pdf`;
  doc.save(filename);
}
